//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lunabotics.OCU.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class CameraSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CameraSettings defaultInstance = ((CameraSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CameraSettings())));
        
        public static CameraSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int FrontQuality {
            get {
                return ((int)(this["FrontQuality"]));
            }
            set {
                this["FrontQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10002")]
        public int FrontReceivePort {
            get {
                return ((int)(this["FrontReceivePort"]));
            }
            set {
                this["FrontReceivePort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int RearQuality {
            get {
                return ((int)(this["RearQuality"]));
            }
            set {
                this["RearQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10004")]
        public int RearReceivePort {
            get {
                return ((int)(this["RearReceivePort"]));
            }
            set {
                this["RearReceivePort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int BucketCameraQuality {
            get {
                return ((int)(this["BucketCameraQuality"]));
            }
            set {
                this["BucketCameraQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BucketCameraFrameRate {
            get {
                return ((int)(this["BucketCameraFrameRate"]));
            }
            set {
                this["BucketCameraFrameRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10006")]
        public int BucketCameraPort {
            get {
                return ((int)(this["BucketCameraPort"]));
            }
            set {
                this["BucketCameraPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int FrontFrameRate {
            get {
                return ((int)(this["FrontFrameRate"]));
            }
            set {
                this["FrontFrameRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RearFrameRate {
            get {
                return ((int)(this["RearFrameRate"]));
            }
            set {
                this["RearFrameRate"] = value;
            }
        }
    }
}
